### ISSUE TITLE
Purplane Support Question

### ISSUE THREAD

**Issue by MoistPencil** [TECHNOVE/Purplane#2]
I am curious if this is gonna be kept up-to-date and have long time support? Also if you need any donations to keep Purplane going lmk because I am willing to pitch in some money.

**Comment by katekerllenevich** [comment]
> I am curious if this is gonna be kept up-to-date and have long time support?

Yes! I plan on updating Purpur and the patches whenever they come out (Usually a couple hours), unless ofc my computer is dead lol.
> Also if you need any donations to keep Purplane going lmk because I am willing to pitch in some money.

Money is not an issue and *hopefully* never will be. This is my hobby, I don't really need (or want) peoples money.
